---
title: "Midterm Momentum"
subtitle: "Can Grassroots Energy Override Historical Trends?"
author: 
  - name: "Lowell Monis"
  - affiliation: "Michigan State University"
  - email: "monislow@msu.edu"

date: "March 31, 2025"

output:
  html_document:
    theme: "readable"  # Choose from default themes like default, cerulean, journal, flatly, readable, spacelab, united, cosmo, lumen, paper, sandstone, simplex, yeti
    highlight: "tango"  # Code syntax highlighting style (default, tango, pygments, kate, monochrome, espresso, zenburn, haddock, breezedark, textmate)
    
    toc: true 
    toc_depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: true
    
    code_folding: "hide"  # Options: "none", "show", "hide"
    code_download: true  # Adds a download button for R code
    
    self_contained: true
    number_sections: false
    df_print: "paged"  # (paged, default, tibble)

# Bibliography and Citations (Optional)
#bibliography: references.bib  # Path to your BibTeX file
#csl: apa.csl  # Citation Style Language file

# Advanced Customization
params:
  version: 1.0
# data_source: "path/to/data"

tags: 
  - "data-science"
  - "electoral-politics"
  - "elections"
  - "politics"
  - "american-politics"
  - "midterms"
  - "democrat"
  - "republican"
  - "partisan"
  - "blog"

keywords:
  - "reproducible research"
  - "graphic detail"
  - "elections"
  - "American politics"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message = FALSE, error = FALSE, warning = FALSE)
```

Or more importantly, can street mobilization be an electoral weathervane?

```{r echo=FALSE}
library(downloadthis)
download_link(
  link = "https://lowell-monis.github.io/ccc-proj/midterm-momentum.pdf",
  button_label = "View Graphic Detail",
  button_type = "primary",
  has_icon = TRUE,
  icon = "fa-solid fa-folder-open",
  self_contained = TRUE
)
download_link(
  link = "https://github.com/lowell-monis/ccc-proj/raw/main/midterm-momentum.pdf",
  button_label = "Download Graphic Detail",
  button_type = "primary",
  has_icon = TRUE,
  icon = "fa-solid fa-download",
  self_contained = TRUE
)
```